Repository be15-fin-tomato/be15-fin-tomato-katchup-FE, pull requests merged in 2025-07, with the labels that each got.

#90 refactor: 인플루언서 등록 페이지 수정
  src/features/user/components/InfluencerFormModal.vue
Labels: fix

#92 chore: 로그인, 로그아웃 연동
  src/components/common/UserPanel.vue
  src/features/user/api.js
  src/features/user/views/LoginView.vue
  src/main.js
  src/plugin/axios.js
  src/router/index.js
  src/stores/auth.js
Labels: feat

#93 [연동] 견적 연동
  src/components/common/SearchPopup.vue
  src/components/layout/OpinionBar.vue
  src/features/campaign/api.js
  src/features/campaign/components/DetailReferenceList.vue
  src/features/campaign/components/SalesCards.vue
  src/features/campaign/components/SalesForm.vue
  src/features/campaign/utils/structedForm.js
  src/features/campaign/views/ProposalDetail.vue
  src/features/campaign/views/ProposalList.vue
  src/features/campaign/views/QuotationDetail.vue
  src/features/campaign/views/QuotationList.vue
  src/features/contract/components/SendEmail.vue
  src/utils/openSearchPopup.js
Labels: feat

#96 Tmt 209 fe 회원 및 마이페이지 연동 구현
  src/components/common/UserPanel.vue
  src/features/mypage/api.js
  src/features/mypage/components/ExchangePassword.vue
  src/features/mypage/views/MyPageView.vue
  src/features/user/api.js
  src/features/user/views/LoginView.vue
  src/features/user/views/findPasswordView.vue
Labels: feat

#98 Tmt 210 fe 알림 연동 구현
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.vue
  src/components/common/UserPanel.vue
  src/features/user/api.js
  src/features/user/views/LoginView.vue
  src/utils/token.js
Labels: feat

#97 feat/ 채팅 전송 기능 구현 완료
  package-lock.json
  package.json
  src/features/chat/components/ChatListModal.vue
  src/features/chat/components/ChatRoom.vue
  vite.config.js
Labels: feat

#99 Tmt 122 fe 고객사 검색 필터링 사이드바 구현 및 연동
  src/components/common/PagingBar.vue
  src/features/advertisement/api.js
  src/features/advertisement/components/ClientFiltering.vue
  src/features/advertisement/views/ClientListView.vue
Labels: feat

#106 Tmt 218 fe 인플루언서 목록 조회 대시보드
  package-lock.json
  src/components/common/InfluencerCard.vue
  src/constants/tags.js
  src/features/influencer/api.js
  src/features/influencer/components/InfluencerCategory.vue
  src/features/influencer/views/InfluencerListView.vue
Labels: feat

#105 Tmt 215 be 만족도 조사 연동 구현
  src/components/common/UserPanel.vue
  src/features/mypage/views/MyPageView.vue
  src/features/user/api.js
  src/features/user/components/EmailCard.vue
  src/features/user/components/Filtering.vue
  src/features/user/views/EmailSystemView.vue
Labels: feat

#107 Fix/satisfaction
  src/features/user/components/EmailCard.vue
Labels: fix

#108 Fix/router
  src/features/dashboard/views/InstagramDashboardView.vue
  src/features/dashboard/views/YoutubeDashboardView.vue
Labels: fix

#110 Tmt 125 fe 고객사 및 사원 저장 수정 페이지 로직 변경 및 연동
  src/features/advertisement/api.js
  src/features/advertisement/components/ClientCreateForm.vue
  src/features/advertisement/views/ClientCreateView.vue
Labels: feat, fix

#116 Tmt 237 연동 인플루언서 관리 연동
  src/components/common/InfluencerManagementCard.vue
  src/features/user/api.js
  src/features/user/views/InfluencerManagementView.vue
Labels: feat

#117 Tmt 233 fe 인플루언서 채널 정보 api 연동
  src/components/common/InfluencerCard.vue
  src/features/influencer/api.js
  src/features/influencer/views/InfluencerListView.vue
Labels: feat, fix

#120 Tmt 241 채팅 모든페이지에 띄우기
  src/App.vue
  src/features/main/views/Main.vue
  src/features/user/views/InfluencerManagementView.vue
Labels: fix

#115 Tmt 234 fe 계약 완료 목록 페이지 연동
  src/features/contract/api.js
  src/features/contract/components/ContractFiltering.vue
  src/features/contract/components/ContractUploadModal.vue
  src/features/contract/components/PasswordModal.vue
  src/features/contract/views/ContractListView.vue
Labels: feat

#123 Tmt 251 연동 채팅 세부사항 수정
  src/features/chat/components/ChatListModal.vue
Labels: fix

#122 Tmt 228 fe 고객사와 사원 정보 조회 및 수정 연동
  package-lock.json
  src/features/advertisement/api.js
  src/features/advertisement/components/ClientCard.vue
  src/features/advertisement/components/ClientCompanyForm.vue
  src/features/advertisement/router.js
  src/features/advertisement/views/ClientCreateView.vue
  src/features/advertisement/views/ClientDetailView.vue
Labels: feat, fix

#125 Tmt 255 연동 캠페인 성과 목록 연동
  src/features/campaign/components/SalesCards.vue
  src/features/contract/components/SendEmail.vue
  src/features/dashboard/api.js
  src/features/dashboard/components/CampaignResultCard.vue
  src/features/dashboard/views/CampaignResultListView.vue
  src/features/user/views/InfluencerManagementView.vue
Labels: feat

#126 Tmt 231 fe 고객사 삭제 UI 구현 및 연동
  src/features/advertisement/api.js
  src/features/advertisement/components/ClientCompanyForm.vue
  src/features/advertisement/views/ClientDetailView.vue
Labels: feat

#128 파이프라인 에러 처리 수정
  src/App.vue
  src/components/common/SearchPopup.vue
  src/components/layout/CommonFiltering.vue
  src/components/layout/SalesFiltering.vue
  src/features/campaign/components/DetailReferenceList.vue
  src/features/campaign/components/SalesForm.vue
  src/features/campaign/utils/validator.js
  src/features/campaign/views/ContractCreate.vue
  src/features/campaign/views/ContractDetail.vue
  src/features/campaign/views/ProposalCreate.vue
  src/features/campaign/views/ProposalDetail.vue
  src/features/campaign/views/QuotationCreate.vue
  src/features/campaign/views/QuotationDetail.vue
  src/features/campaign/views/RevenueCreate.vue
  src/features/campaign/views/RevenueDetail.vue
  src/features/user/components/Filtering.vue
Labels: fix

#129 fix: 사원 수정 시 복제되는 문제 해결
  src/features/advertisement/components/ClientCompanyForm.vue
Labels: fix

#134 Fix/campaign list
  src/components/layout/HorizontalFiltering.vue
  src/features/campaign/components/CampaignForm.vue
  src/features/campaign/components/CampaignHistory.vue
  src/features/campaign/views/CampaignDetail.vue
Labels: fix

#137 feat: 카테고리 추가
  src/components/common/InfluencerManagementFilter.vue
  src/features/user/api.js
  src/features/user/views/InfluencerManagementView.vue
Labels: fix

#143 성과 목록 수정
  src/features/dashboard/views/CampaignResultListView.vue
Labels: feat

#142 Tmt 271 fe 인플루언서 대시보드 목록 로딩 처리
  src/components/common/InfluencerCard.vue
  src/features/influencer/views/InfluencerListView.vue
Labels: fix

#149 Tmt 276 연동 성과 대시보드
  src/features/dashboard/api.js
  src/features/dashboard/components/CampaignHeaderCard.vue
  src/features/dashboard/components/GoogleSearchData.vue
  src/features/dashboard/components/NaverSearchData.vue
  src/features/dashboard/components/chart/CampaignVideoSummary.vue
  src/features/dashboard/components/chart/TrafficSourcesChart.vue
  src/features/dashboard/components/chart/YoutubeAnalyticsChart.vue
  src/features/dashboard/views/CampaignResultDashboardView.vue
  src/features/dashboard/views/CampaignResultListView.vue
Labels: feat

#153 Tmt 274 fe 인스타그램 대시보드 api 연동
  package-lock.json
  src/assets/images/instagram-default-thumbnail.png
  src/features/dashboard/api.js
  src/features/dashboard/components/DashboardBase.vue
  src/features/dashboard/components/DashboardCampaignList.vue
  src/features/dashboard/components/DashboardSummary.vue
  src/features/dashboard/components/PopularPosts.vue
  src/features/dashboard/components/PopularShortForms.vue
  src/features/dashboard/components/chart/AgeChart.vue
  src/features/dashboard/components/chart/AverageChart.vue
  src/features/dashboard/components/chart/FollowerChart.vue
  src/features/dashboard/components/chart/ReachChart.vue
  src/features/dashboard/views/InstagramDashboardView.vue
  src/features/dashboard/views/YoutubeDashboardView.vue
  src/features/influencer/views/InfluencerListView.vue
Labels: feat, fix

#155 파이프라인 인플루언서 이름 안보이는 오류 수정
  src/features/campaign/utils/structedForm.js
Labels: fix

#158 refactor: 알림 toast 교체
  src/features/chat/components/ChatListModal.vue
  src/features/chat/components/ChatRoom.vue
  src/features/contract/views/ContractTemplateView.vue
  src/features/dashboard/views/CampaignResultListView.vue
Labels: fix

#162 Tmt 295 fe 스타일 수정
  src/assets/styles/tailwind.css
  src/features/advertisement/components/ClientFiltering.vue
  src/features/advertisement/views/ClientCreateView.vue
  src/features/advertisement/views/ClientDetailView.vue
  src/features/advertisement/views/ClientListView.vue
  src/features/chat/components/ChatListModal.vue
  src/features/chat/components/ChatRoom.vue
  src/features/contract/views/ContractTemplateView.vue
  src/features/dashboard/views/CampaignResultListView.vue
Labels: feat, fix

#165 Tmt 295 fe 스타일 수정
  src/components/layout/HorizontalFiltering.vue
  src/components/layout/SalesFiltering.vue
  src/features/advertisement/components/ClientFiltering.vue
Labels: fix

#164 Fix: 만족도 조사 페이징바 오류 수정
  src/components/common/PagingBar.vue
  src/features/user/views/EmailSystemView.vue
  src/features/user/views/SurveyListView.vue
Labels: fix

#169 Tmt 289 fe 인플루언서와 유튜브 인스타그램 계정 연동 기능
  src/components/common/InfluencerManagementCard.vue
  src/features/influencer/api.js
  src/features/user/components/YoutubeOAuthCallback.vue
  src/features/user/router.js
  src/features/user/views/InfluencerManagementView.vue
Labels: feat

#171 Fix: 카테고리 선택 필터 수정
  src/features/influencer/views/InfluencerListView.vue
Labels: fix

#177 메일 수정
  src/features/contract/components/SendEmail.vue
Labels: fix

#182 인플루언서 등록/수정 화면 이메일 삭제
  src/features/ai/api.js
  src/features/ai/views/AIRecommendView.vue
  src/features/influencer/components/InfluencerFormModal.vue
Labels: fix

#184 fix: 인플루언서 목록 페이지 스켈레톤 추가
  src/features/influencer/components/InfluencerCardSkeleton.vue
  src/features/influencer/views/InfluencerListView.vue
Labels: feat

#183 Tmt 307 fe 메인 대시보드 라우팅 수정
  src/features/influencer/views/InfluencerManagementView.vue
  src/features/main/components/SalesDashboard.vue
  src/features/main/views/Main.vue
Labels: fix

#187 Tmt 314 fe 인플루언서 대시보드 목록 수정
  src/components/common/InfluencerCard.vue
  src/features/influencer/components/InfluencerCategory.vue
  src/features/influencer/views/InfluencerListView.vue
Labels: fix

#189 refactor : 전체적인 수정
  src/features/chat/components/ChatRoom.vue
  src/features/contract/views/ContractListView.vue
  src/features/dashboard/api.js
  src/features/dashboard/components/AnalyticsFilters.vue
  src/features/dashboard/components/CampaignHeaderCard.vue
  src/features/dashboard/components/chart/RevenueSummary.vue
  src/features/dashboard/components/chart/TrafficSourcesChart.vue
  src/features/dashboard/components/chart/YoutubeAnalyticsChart.vue
  src/features/dashboard/views/CampaignResultDashboardView.vue
  src/features/dashboard/views/CampaignResultListView.vue
Labels: feat

#191 Fix: 만족도조사 페이지 수정
  src/features/user/components/ChartCard.vue
  src/features/user/components/DoughnutChart.vue
  src/features/user/components/EmailCard.vue
  src/features/user/components/Filtering.vue
  src/features/user/components/SatisfactionCard.vue
  src/features/user/views/EmailSystemView.vue
  src/features/user/views/SurveyListView.vue
Labels: fix

#192 템플릿 목록
  src/features/contract/views/ContractTemplateView.vue
  src/features/dashboard/components/CampaignHeaderCard.vue
Labels: fix

#193 파이프라인 오류 수정
  src/assets/styles/tailwind.css
  src/components/common/SearchPopup.vue
  src/components/layout/OpinionBar.vue
  src/components/layout/SalesFiltering.vue
  src/features/ai/components/AIInfluencerCard.vue
  src/features/ai/components/AddToListupModal.vue
  src/features/ai/components/AddedInfluencers.vue
  src/features/ai/views/AIRecommendView.vue
  src/features/campaign/components/ProposalAccordionItem.vue
  src/features/campaign/components/SalesCards.vue
  src/features/campaign/views/ContractCreate.vue
  src/features/campaign/views/ContractDetail.vue
  src/features/campaign/views/ContractList.vue
  src/features/campaign/views/ListUpList.vue
  src/features/campaign/views/ProposalCreate.vue
  src/features/campaign/views/ProposalDetail.vue
  src/features/campaign/views/ProposalList.vue
  src/features/campaign/views/QuotationCreate.vue
  src/features/campaign/views/QuotationDetail.vue
  src/features/campaign/views/QuotationList.vue
  src/features/campaign/views/RevenueCreate.vue
  src/features/campaign/views/RevenueDetail.vue
  src/features/campaign/views/RevenueList.vue
  src/main.js
  src/stores/auth.js
Labels: fix

#194 Fix: 캠페인 목록 체크된 단계까지 나오게 변경
  src/components/layout/HorizontalFiltering.vue
  src/features/campaign/components/PipelineDiagram.vue
  src/features/contract/components/ContractUploadModal.vue
  src/features/contract/views/ContractListView.vue
Labels: fix

#198 Fix: 로그인 버튼 클릭시 로딩중 추가
  src/features/user/views/LoginView.vue
Labels: fix

#202 Fix: 배포환경일때 배포 url로 요청하게 수정
  src/features/user/api.js
Labels: fix
